apiVersion: apps/v1
kind: Deployment
metadata:
  name: candidate-api
  labels:
    app: candidate-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candidate-api
  template:
    metadata:
      labels:
        app: candidate-api
    spec:
      containers:
      - name: candidate-api
        image: vladpantea/candidate-api:v0.0.1
        ports:
        - containerPort: 5080