apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    app: {{ .Values.metadata.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.name }}      
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.name }}
    spec:    
      containers:
      - name: {{ .Values.metadata.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"        
        ports:
        - name: app-port
          containerPort: {{ .Values.containerPort }}              
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}   
            port: app-port
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }} 
            port: app-port
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }} 
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }} 
        env:
        # Define the environment variable
        - name: PORT
          value: "{{ .Values.containerPort }}"
        - name: UPLOAD_FOLDER
          value: {{ .Values.env.uploadFolder }}
        - name: NODE_ENV
          value: {{ .Values.env.nodeEnv }}
        - name: MONGODB_SERVER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: MONGODB_SERVER
        - name: MONGODB_SERVER_PORT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: MONGODB_SERVER_PORT
        - name: MONGODB_DB
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: MONGODB_DB
        - name: MONGODB_DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: MONGODB_DB_USER
        - name: MONGODB_DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: MONGODB_DB_PASS
