apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  MONGODB_SERVER: {{ .Values.secret.mongodbServer }}
  MONGODB_SERVER_PORT: {{ .Values.secret.mongodbServerPort }}
  MONGODB_DB: {{ .Values.secret.mongodbDatabaseName }}
  MONGODB_DB_USER: {{ .Values.secret.mongodbDatabaseUser }}
  MONGODB_DB_PASS: {{ .Values.secret.mongodbDatabasePassword }}