apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}  
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.metadata.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  
